#!/bin/bash
SOURCE_HOME=/home/ark/Projects/CryptoStat
JDK_HOME=/opt/jdk1.7
SOURCEPATH=$SOURCE_HOME/lib
BOOTCLASSPATH=$JDK_HOME/jre/lib/rt.jar
DOCDIR=$SOURCE_HOME/doc
LINKURL1=https://docs.oracle.com/javase/7/docs/api/
#LINKURL2=http://www.cs.rit.edu/~ark/pj2/doc/
LINKURL2=file:///home/ark/Projects/pj2/doc/
OVERVIEWFILE=$SOURCEPATH/overview.html
if [[ -d $DOCDIR ]]
then
    rm -r $DOCDIR/*
else
    echo "Documentation directory $DOCDIR does not exist."
    exit 1
fi
$JDK_HOME/bin/javadoc \
-sourcepath $SOURCEPATH \
-bootclasspath $BOOTCLASSPATH \
-d $DOCDIR \
-use \
-splitindex \
-doctitle "THE CRYPTOSTAT LIBRARY" \
-link $LINKURL1 \
-link $LINKURL2 \
-windowtitle "CryptoStat Library Documentation" \
-bottom "<FONT SIZE=\"-2\">Copyright &copy; 2016&ndash;2019 by Alan Kaminsky. All rights reserved. Send comments to ark</FONT><FONT SIZE=\"1\" COLOR=\"#FFFFFF\">&shy;</FONT><FONT SIZE=\"-2\">&#64;</FONT><FONT SIZE=\"1\" COLOR=\"#FFFFFF\">&shy;</FONT><FONT SIZE=\"-2\">cs.rit.edu.</FONT>" \
-overview $OVERVIEWFILE \
lib/*.java \
edu.rit.crst \
edu.rit.aes \
edu.rit.sha1 \
edu.rit.sha2 \
edu.rit.sha3 \
edu.rit.util \


